@echo off
setlocal enabledelayedexpansion

echo ===================================================
echo   Elara POS Standalone Bundle Creator
echo ===================================================
echo.

set DIST_DIR=%~dp0DIST
set APP_DIR=%DIST_DIR%\ElaraPOS

if exist "%DIST_DIR%" rd /s /q "%DIST_DIR%"
mkdir "%APP_DIR%"

echo [1/4] Building Flutter Desktop (Release)...
cd /d "%~dp0pos_desktop"
call flutter clean
call flutter pub get
call flutter build windows --release
if %ERRORLEVEL% NEQ 0 (
    echo Flutter build failed!
    pause
    exit /b %ERRORLEVEL%
)

echo [2/4] Copying Flutter App files...
xcopy /E /I /Y "%~dp0pos_desktop\build\windows\x64\runner\Release\*" "%APP_DIR%\"

echo [3/4] Preparing Backend...
mkdir "%APP_DIR%\backend"
xcopy /E /I /Y "%~dp0config" "%APP_DIR%\backend\config"
xcopy /E /I /Y "%~dp0middleware" "%APP_DIR%\backend\middleware"
xcopy /E /I /Y "%~dp0models" "%APP_DIR%\backend\models"
xcopy /E /I /Y "%~dp0routes" "%APP_DIR%\backend\routes"
xcopy /E /I /Y "%~dp0sockets" "%APP_DIR%\backend\sockets"
xcopy /E /I /Y "%~dp0whatsapp" "%APP_DIR%\backend\whatsapp"
xcopy /E /I /Y "%~dp0public" "%APP_DIR%\backend\public"
if exist "%~dp0client\dist" (
    mkdir "%APP_DIR%\backend\client\dist"
    xcopy /E /I /Y "%~dp0client\dist" "%APP_DIR%\backend\client\dist"
)
copy /Y "%~dp0server.js" "%APP_DIR%\backend\"
copy /Y "%~dp0.env" "%APP_DIR%\backend\"
copy /Y "%~dp0users.json" "%APP_DIR%\backend\"
copy /Y "%~dp0accounts_db.js" "%APP_DIR%\backend\"
if exist "%~dp0accounts.db" copy /Y "%~dp0accounts.db" "%APP_DIR%\backend\"

:: Create a clean package.json for backend (removing mobile deps to avoid MAX_PATH issues)
echo { > "%APP_DIR%\backend\package.json"
echo   "name": "elara-backend", >> "%APP_DIR%\backend\package.json"
echo   "version": "1.0.0", >> "%APP_DIR%\backend\package.json"
echo   "main": "server.js", >> "%APP_DIR%\backend\package.json"
echo   "dependencies": { >> "%APP_DIR%\backend\package.json"
echo     "axios": "^1.13.5", >> "%APP_DIR%\backend\package.json"
echo     "bcryptjs": "^2.4.3", >> "%APP_DIR%\backend\package.json"
echo     "cors": "^2.8.5", >> "%APP_DIR%\backend\package.json"
echo     "dotenv": "^16.4.5", >> "%APP_DIR%\backend\package.json"
echo     "express": "^4.19.2", >> "%APP_DIR%\backend\package.json"
echo     "jsonwebtoken": "^9.0.2", >> "%APP_DIR%\backend\package.json"
echo     "multer": "^2.0.2", >> "%APP_DIR%\backend\package.json"
echo     "mysql2": "^3.9.7", >> "%APP_DIR%\backend\package.json"
echo     "sequelize": "^6.37.3", >> "%APP_DIR%\backend\package.json"
echo     "socket.io": "^4.8.3", >> "%APP_DIR%\backend\package.json"
echo     "socket.io-client": "^4.8.3", >> "%APP_DIR%\backend\package.json"
echo     "swagger-jsdoc": "^6.2.8", >> "%APP_DIR%\backend\package.json"
echo     "swagger-ui-express": "^5.0.0", >> "%APP_DIR%\backend\package.json"
echo     "better-sqlite3": "^11.0.0" >> "%APP_DIR%\backend\package.json"
echo   } >> "%APP_DIR%\backend\package.json"
echo } >> "%APP_DIR%\backend\package.json"
copy /Y "%~dp0users.json" "%APP_DIR%\backend\"
copy /Y "%~dp0accounts_db.js" "%APP_DIR%\backend\"
if exist "%~dp0accounts.db" copy /Y "%~dp0accounts.db" "%APP_DIR%\backend\"

echo [4/5] Installing Backend Dependencies...
cd /d "%APP_DIR%\backend"
call npm install --production
if %ERRORLEVEL% NEQ 0 (
    echo npm install failed!
    pause
    exit /b %ERRORLEVEL%
)
cd /d "%~dp0"

:: Note: AI and Accounts are integrated into the main backend above.

echo [5/5] Creating Launchers...

:: ── START_POS.vbs ──────────────────────────────────────────
echo Set WshShell = CreateObject("WScript.Shell") > "%APP_DIR%\START_POS.vbs"
echo Set fso = CreateObject("Scripting.FileSystemObject") >> "%APP_DIR%\START_POS.vbs"
echo. >> "%APP_DIR%\START_POS.vbs"
echo ' ── OLLAMA CHECK ───────────────────────────────────── >> "%APP_DIR%\START_POS.vbs"
echo Dim ollamaInstalled >> "%APP_DIR%\START_POS.vbs"
echo ollamaInstalled = False >> "%APP_DIR%\START_POS.vbs"
echo. >> "%APP_DIR%\START_POS.vbs"
echo If fso.FileExists("C:\Users\" ^& WshShell.ExpandEnvironmentStrings("%%USERNAME%%") ^& "\AppData\Local\Programs\Ollama\ollama.exe") Then >> "%APP_DIR%\START_POS.vbs"
echo     ollamaInstalled = True >> "%APP_DIR%\START_POS.vbs"
echo ElseIf WshShell.Run("cmd /c where ollama", 0, True) = 0 Then >> "%APP_DIR%\START_POS.vbs"
echo     ollamaInstalled = True >> "%APP_DIR%\START_POS.vbs"
echo End If >> "%APP_DIR%\START_POS.vbs"
echo. >> "%APP_DIR%\START_POS.vbs"
echo If Not ollamaInstalled Then >> "%APP_DIR%\START_POS.vbs"
echo     Dim answer >> "%APP_DIR%\START_POS.vbs"
echo     answer = MsgBox("Ollama (Local AI) is not installed on this PC." ^& vbCrLf ^& vbCrLf ^& _ >> "%APP_DIR%\START_POS.vbs"
echo                     "Elais AI needs Ollama to work in offline mode." ^& vbCrLf ^& vbCrLf ^& _ >> "%APP_DIR%\START_POS.vbs"
echo                     "Would you like to automatically download and install Ollama now?" ^& vbCrLf ^& _ >> "%APP_DIR%\START_POS.vbs"
echo                     "(Requires internet connection, approx 150MB)", _ >> "%APP_DIR%\START_POS.vbs"
echo                     vbYesNo + vbQuestion, "Elais AI - Ollama Not Found") >> "%APP_DIR%\START_POS.vbs"
echo. >> "%APP_DIR%\START_POS.vbs"
echo     If answer = vbYes Then >> "%APP_DIR%\START_POS.vbs"
echo         MsgBox "Downloading Ollama installer... Please wait." ^& vbCrLf ^& vbCrLf ^& _ >> "%APP_DIR%\START_POS.vbs"
echo                "A download window will open. Once it finishes, Ollama will install silently.", _ >> "%APP_DIR%\START_POS.vbs"
echo                vbInformation, "Installing Ollama" >> "%APP_DIR%\START_POS.vbs"
echo. >> "%APP_DIR%\START_POS.vbs"
echo         Dim downloadPath >> "%APP_DIR%\START_POS.vbs"
echo         downloadPath = WshShell.ExpandEnvironmentStrings("%%TEMP%%") ^& "\OllamaSetup.exe" >> "%APP_DIR%\START_POS.vbs"
echo. >> "%APP_DIR%\START_POS.vbs"
echo         WshShell.Run "powershell -Command ""Invoke-WebRequest -Uri 'https://ollama.com/download/OllamaSetup.exe' -OutFile '" ^& downloadPath ^& "' -UseBasicParsing""", 1, True >> "%APP_DIR%\START_POS.vbs"
echo. >> "%APP_DIR%\START_POS.vbs"
echo         If fso.FileExists(downloadPath) Then >> "%APP_DIR%\START_POS.vbs"
echo             MsgBox "Download complete! Installing Ollama silently...", vbInformation, "Installing Ollama" >> "%APP_DIR%\START_POS.vbs"
echo             WshShell.Run """" ^& downloadPath ^& """ /SILENT", 1, True >> "%APP_DIR%\START_POS.vbs"
echo             WScript.Sleep 5000 >> "%APP_DIR%\START_POS.vbs"
echo. >> "%APP_DIR%\START_POS.vbs"
echo             Dim pullAnswer >> "%APP_DIR%\START_POS.vbs"
echo             pullAnswer = MsgBox("Ollama installed!" ^& vbCrLf ^& vbCrLf ^& _ >> "%APP_DIR%\START_POS.vbs"
echo                                 "Now we need to download the AI model (phi3:mini, approx 2.3GB)." ^& vbCrLf ^& _ >> "%APP_DIR%\START_POS.vbs"
echo                                 "This only happens once. Download now?", _ >> "%APP_DIR%\START_POS.vbs"
echo                                 vbYesNo + vbInformation, "Download AI Model") >> "%APP_DIR%\START_POS.vbs"
echo. >> "%APP_DIR%\START_POS.vbs"
echo             If pullAnswer = vbYes Then >> "%APP_DIR%\START_POS.vbs"
echo                 MsgBox "Downloading phi3:mini model... A terminal window will open." ^& vbCrLf ^& _ >> "%APP_DIR%\START_POS.vbs"
echo                        "Wait for it to finish and close automatically.", _ >> "%APP_DIR%\START_POS.vbs"
echo                        vbInformation, "Downloading Model" >> "%APP_DIR%\START_POS.vbs"
echo                 WshShell.Run "cmd /c ollama pull phi3:mini", 1, True >> "%APP_DIR%\START_POS.vbs"
echo                 WshShell.Run "powershell -Command ""[Environment]::SetEnvironmentVariable('PATH', [Environment]::GetEnvironmentVariable('PATH','Machine') + ';C:\Users\' + $env:USERNAME + '\AppData\Local\Programs\Ollama', 'Machine')""", 0, True >> "%APP_DIR%\START_POS.vbs"
echo                 WshShell.Run "ollama serve", 0, False >> "%APP_DIR%\START_POS.vbs"
echo                 WScript.Sleep 3000 >> "%APP_DIR%\START_POS.vbs"
echo                 MsgBox "Elais AI is ready! Starting ElaraPOS now.", vbInformation, "Setup Complete" >> "%APP_DIR%\START_POS.vbs"
echo             Else >> "%APP_DIR%\START_POS.vbs"
echo                 MsgBox "You can download the model later by opening a terminal and running:" ^& vbCrLf ^& vbCrLf ^& _ >> "%APP_DIR%\START_POS.vbs"
echo                        "    ollama pull phi3:mini" ^& vbCrLf ^& vbCrLf ^& _ >> "%APP_DIR%\START_POS.vbs"
echo                        "Elais will show as offline until a model is downloaded.", _ >> "%APP_DIR%\START_POS.vbs"
echo                        vbInformation, "Model Skipped" >> "%APP_DIR%\START_POS.vbs"
echo             End If >> "%APP_DIR%\START_POS.vbs"
echo         Else >> "%APP_DIR%\START_POS.vbs"
echo             MsgBox "Download failed. Please check your internet connection and try again.", _ >> "%APP_DIR%\START_POS.vbs"
echo                    vbCritical, "Download Failed" >> "%APP_DIR%\START_POS.vbs"
echo         End If >> "%APP_DIR%\START_POS.vbs"
echo. >> "%APP_DIR%\START_POS.vbs"
echo     Else >> "%APP_DIR%\START_POS.vbs"
echo         MsgBox "No problem! Here are your two options:" ^& vbCrLf ^& vbCrLf ^& _ >> "%APP_DIR%\START_POS.vbs"
echo                "──────────────────────────────────────" ^& vbCrLf ^& _ >> "%APP_DIR%\START_POS.vbs"
echo                "OPTION 1 — Install Ollama manually:" ^& vbCrLf ^& _ >> "%APP_DIR%\START_POS.vbs"
echo                "  1. Go to https://ollama.com/download" ^& vbCrLf ^& _ >> "%APP_DIR%\START_POS.vbs"
echo                "  2. Download and run OllamaSetup.exe" ^& vbCrLf ^& _ >> "%APP_DIR%\START_POS.vbs"
echo                "  3. Open a terminal and run:" ^& vbCrLf ^& _ >> "%APP_DIR%\START_POS.vbs"
echo                "       ollama pull phi3:mini" ^& vbCrLf ^& _ >> "%APP_DIR%\START_POS.vbs"
echo                "  4. Restart ElaraPOS" ^& vbCrLf ^& vbCrLf ^& _ >> "%APP_DIR%\START_POS.vbs"
echo                "──────────────────────────────────────" ^& vbCrLf ^& _ >> "%APP_DIR%\START_POS.vbs"
echo                "OPTION 2 — Use Cloud AI instead:" ^& vbCrLf ^& _ >> "%APP_DIR%\START_POS.vbs"
echo                "  1. Go to https://ollama.com and create an account" ^& vbCrLf ^& _ >> "%APP_DIR%\START_POS.vbs"
echo                "  2. Generate an API key under your profile" ^& vbCrLf ^& _ >> "%APP_DIR%\START_POS.vbs"
echo                "  3. In ElaraPOS Settings > Elais AI:" ^& vbCrLf ^& _ >> "%APP_DIR%\START_POS.vbs"
echo                "       Set AI Source to: Online (Cloud)" ^& vbCrLf ^& _ >> "%APP_DIR%\START_POS.vbs"
echo                "       Paste your API key" ^& vbCrLf ^& _ >> "%APP_DIR%\START_POS.vbs"
echo                "       Set URL: https://ollama.com/api/chat" ^& vbCrLf ^& _ >> "%APP_DIR%\START_POS.vbs"
echo                "       Set Model: qwen3.5" ^& vbCrLf ^& _ >> "%APP_DIR%\START_POS.vbs"
echo                "  4. Click Save and Test Connection" ^& vbCrLf ^& vbCrLf ^& _ >> "%APP_DIR%\START_POS.vbs"
echo                "ElaraPOS will now start without AI features.", _ >> "%APP_DIR%\START_POS.vbs"
echo                vbInformation, "Elais AI Setup Options" >> "%APP_DIR%\START_POS.vbs"
echo     End If >> "%APP_DIR%\START_POS.vbs"
echo. >> "%APP_DIR%\START_POS.vbs"
echo Else >> "%APP_DIR%\START_POS.vbs"
echo     If WshShell.Run("cmd /c netstat -ano ^| findstr :11434", 0, True) ^<^> 0 Then >> "%APP_DIR%\START_POS.vbs"
echo         WshShell.Run "ollama serve", 0, False >> "%APP_DIR%\START_POS.vbs"
echo         WScript.Sleep 2000 >> "%APP_DIR%\START_POS.vbs"
echo     End If >> "%APP_DIR%\START_POS.vbs"
echo End If >> "%APP_DIR%\START_POS.vbs"
echo. >> "%APP_DIR%\START_POS.vbs"
echo ' ── START XAMPP ─────────────────────────────────────── >> "%APP_DIR%\START_POS.vbs"
echo If WshShell.Run("cmd /c tasklist ^| findstr /I apache_httpd.exe", 0, True) ^<^> 0 Then >> "%APP_DIR%\START_POS.vbs"
echo     WshShell.Run "C:\xampp\xampp_start.exe", 0, False >> "%APP_DIR%\START_POS.vbs"
echo     WScript.Sleep 3000 >> "%APP_DIR%\START_POS.vbs"
echo End If >> "%APP_DIR%\START_POS.vbs"
echo. >> "%APP_DIR%\START_POS.vbs"
echo If WshShell.Run("cmd /c netstat -ano ^| findstr :3306", 0, True) ^<^> 0 Then >> "%APP_DIR%\START_POS.vbs"
echo     WshShell.Run "C:\xampp\mysql\bin\mysqld.exe --port=3306", 0, False >> "%APP_DIR%\START_POS.vbs"
echo     WScript.Sleep 3000 >> "%APP_DIR%\START_POS.vbs"
echo End If >> "%APP_DIR%\START_POS.vbs"
echo. >> "%APP_DIR%\START_POS.vbs"
echo ' ── START BACKEND ───────────────────────────────────── >> "%APP_DIR%\START_POS.vbs"
echo WshShell.Run "cmd /c cd backend ^& node server.js", 0, False >> "%APP_DIR%\START_POS.vbs"
echo WScript.Sleep 5000 >> "%APP_DIR%\START_POS.vbs"
echo. >> "%APP_DIR%\START_POS.vbs"
echo ' ── START POS APP ───────────────────────────────────── >> "%APP_DIR%\START_POS.vbs"
echo WshShell.Run "elara_pos.exe", 1, True >> "%APP_DIR%\START_POS.vbs"

:: ── LAUNCHER.bat ───────────────────────────────────────────
echo @echo off > "%APP_DIR%\LAUNCHER.bat"
echo echo ================================================= >> "%APP_DIR%\LAUNCHER.bat"
echo echo   Elara POS Launcher (with Elais AI) >> "%APP_DIR%\LAUNCHER.bat"
echo echo ================================================= >> "%APP_DIR%\LAUNCHER.bat"
echo echo. >> "%APP_DIR%\LAUNCHER.bat"
echo. >> "%APP_DIR%\LAUNCHER.bat"
echo :: ── OLLAMA CHECK ─────────────────────────────────── >> "%APP_DIR%\LAUNCHER.bat"
echo set OLLAMA_FOUND=0 >> "%APP_DIR%\LAUNCHER.bat"
echo where ollama ^>nul 2^>^&1 ^&^& set OLLAMA_FOUND=1 >> "%APP_DIR%\LAUNCHER.bat"
echo if exist "%%LOCALAPPDATA%%\Programs\Ollama\ollama.exe" set OLLAMA_FOUND=1 >> "%APP_DIR%\LAUNCHER.bat"
echo. >> "%APP_DIR%\LAUNCHER.bat"
echo if %%OLLAMA_FOUND%%==0 ( >> "%APP_DIR%\LAUNCHER.bat"
echo     echo [Elais] Ollama is NOT installed on this PC. >> "%APP_DIR%\LAUNCHER.bat"
echo     echo. >> "%APP_DIR%\LAUNCHER.bat"
echo     choice /C YN /M "Would you like to automatically download and install Ollama now?" >> "%APP_DIR%\LAUNCHER.bat"
echo     if %%ERRORLEVEL%%==1 ( >> "%APP_DIR%\LAUNCHER.bat"
echo         echo. >> "%APP_DIR%\LAUNCHER.bat"
echo         echo [Elais] Downloading Ollama installer... >> "%APP_DIR%\LAUNCHER.bat"
echo         powershell -Command "Invoke-WebRequest -Uri 'https://ollama.com/download/OllamaSetup.exe' -OutFile '%%TEMP%%\OllamaSetup.exe' -UseBasicParsing" >> "%APP_DIR%\LAUNCHER.bat"
echo         if exist "%%TEMP%%\OllamaSetup.exe" ( >> "%APP_DIR%\LAUNCHER.bat"
echo             echo [Elais] Installing Ollama silently... >> "%APP_DIR%\LAUNCHER.bat"
echo             "%%TEMP%%\OllamaSetup.exe" /SILENT >> "%APP_DIR%\LAUNCHER.bat"
echo             timeout /t 5 /nobreak ^>nul >> "%APP_DIR%\LAUNCHER.bat"
echo             echo. >> "%APP_DIR%\LAUNCHER.bat"
echo             choice /C YN /M "Ollama installed! Download AI model now (phi3:mini, approx 2.3GB)?" >> "%APP_DIR%\LAUNCHER.bat"
echo             if %%ERRORLEVEL%%==1 ( >> "%APP_DIR%\LAUNCHER.bat"
echo                 echo [Elais] Downloading phi3:mini model... >> "%APP_DIR%\LAUNCHER.bat"
echo                 ollama pull phi3:mini >> "%APP_DIR%\LAUNCHER.bat"
echo                 powershell -Command "[Environment]::SetEnvironmentVariable('PATH', [Environment]::GetEnvironmentVariable('PATH','Machine') + ';%%LOCALAPPDATA%%\Programs\Ollama', 'Machine')" >> "%APP_DIR%\LAUNCHER.bat"
echo                 echo [Elais] Starting Ollama service... >> "%APP_DIR%\LAUNCHER.bat"
echo                 start /min cmd /c "ollama serve" >> "%APP_DIR%\LAUNCHER.bat"
echo                 timeout /t 3 /nobreak ^>nul >> "%APP_DIR%\LAUNCHER.bat"
echo                 echo [Elais] AI is ready! >> "%APP_DIR%\LAUNCHER.bat"
echo             ) else ( >> "%APP_DIR%\LAUNCHER.bat"
echo                 echo [Elais] Model skipped. Run "ollama pull phi3:mini" later to enable AI. >> "%APP_DIR%\LAUNCHER.bat"
echo             ) >> "%APP_DIR%\LAUNCHER.bat"
echo         ) else ( >> "%APP_DIR%\LAUNCHER.bat"
echo             echo [Elais] Download failed. Check your internet and try again. >> "%APP_DIR%\LAUNCHER.bat"
echo         ) >> "%APP_DIR%\LAUNCHER.bat"
echo     ) else ( >> "%APP_DIR%\LAUNCHER.bat"
echo         echo. >> "%APP_DIR%\LAUNCHER.bat"
echo         echo [Elais] No problem! Two ways to set up AI later: >> "%APP_DIR%\LAUNCHER.bat"
echo         echo. >> "%APP_DIR%\LAUNCHER.bat"
echo         echo   OPTION 1 - Install Ollama manually: >> "%APP_DIR%\LAUNCHER.bat"
echo         echo     1. Go to https://ollama.com/download >> "%APP_DIR%\LAUNCHER.bat"
echo         echo     2. Run OllamaSetup.exe >> "%APP_DIR%\LAUNCHER.bat"
echo         echo     3. Open terminal and run: ollama pull phi3:mini >> "%APP_DIR%\LAUNCHER.bat"
echo         echo     4. Restart ElaraPOS >> "%APP_DIR%\LAUNCHER.bat"
echo         echo. >> "%APP_DIR%\LAUNCHER.bat"
echo         echo   OPTION 2 - Use Cloud AI: >> "%APP_DIR%\LAUNCHER.bat"
echo         echo     1. Go to https://ollama.com and create an account >> "%APP_DIR%\LAUNCHER.bat"
echo         echo     2. Generate an API key under your profile >> "%APP_DIR%\LAUNCHER.bat"
echo         echo     3. In ElaraPOS Settings ^> Elais AI: >> "%APP_DIR%\LAUNCHER.bat"
echo         echo          Set Source: Online (Cloud) >> "%APP_DIR%\LAUNCHER.bat"
echo         echo          Paste your API key >> "%APP_DIR%\LAUNCHER.bat"
echo         echo          URL: https://ollama.com/api/chat >> "%APP_DIR%\LAUNCHER.bat"
echo         echo          Model: qwen3.5 >> "%APP_DIR%\LAUNCHER.bat"
echo         echo     4. Click Save and Test Connection >> "%APP_DIR%\LAUNCHER.bat"
echo         echo. >> "%APP_DIR%\LAUNCHER.bat"
echo         echo Starting ElaraPOS without AI features... >> "%APP_DIR%\LAUNCHER.bat"
echo         timeout /t 4 /nobreak ^>nul >> "%APP_DIR%\LAUNCHER.bat"
echo     ) >> "%APP_DIR%\LAUNCHER.bat"
echo ) else ( >> "%APP_DIR%\LAUNCHER.bat"
echo     echo [Elais] Ollama found. Checking if running... >> "%APP_DIR%\LAUNCHER.bat"
echo     netstat -ano ^| findstr :11434 ^>nul 2^>^&1 >> "%APP_DIR%\LAUNCHER.bat"
echo     if %%ERRORLEVEL%% NEQ 0 ( >> "%APP_DIR%\LAUNCHER.bat"
echo         echo [Elais] Starting Ollama service... >> "%APP_DIR%\LAUNCHER.bat"
echo         start /min cmd /c "ollama serve" >> "%APP_DIR%\LAUNCHER.bat"
echo         timeout /t 2 /nobreak ^>nul >> "%APP_DIR%\LAUNCHER.bat"
echo     ) else ( >> "%APP_DIR%\LAUNCHER.bat"
echo         echo [Elais] Ollama already running. >> "%APP_DIR%\LAUNCHER.bat"
echo     ) >> "%APP_DIR%\LAUNCHER.bat"
echo ) >> "%APP_DIR%\LAUNCHER.bat"
echo. >> "%APP_DIR%\LAUNCHER.bat"
echo :: ── START XAMPP ──────────────────────────────────── >> "%APP_DIR%\LAUNCHER.bat"
echo tasklist ^| findstr /I "apache_httpd.exe" ^>nul 2^>^&1 >> "%APP_DIR%\LAUNCHER.bat"
echo if %%ERRORLEVEL%% NEQ 0 ( >> "%APP_DIR%\LAUNCHER.bat"
echo     echo Starting XAMPP Apache... >> "%APP_DIR%\LAUNCHER.bat"
echo     start "" "C:\xampp\xampp_start.exe" >> "%APP_DIR%\LAUNCHER.bat"
echo     timeout /t 3 /nobreak ^>nul >> "%APP_DIR%\LAUNCHER.bat"
echo ) else ( >> "%APP_DIR%\LAUNCHER.bat"
echo     echo Apache already running, skipping... >> "%APP_DIR%\LAUNCHER.bat"
echo ) >> "%APP_DIR%\LAUNCHER.bat"
echo. >> "%APP_DIR%\LAUNCHER.bat"
echo netstat -ano ^| findstr :3306 ^>nul 2^>^&1 >> "%APP_DIR%\LAUNCHER.bat"
echo if %%ERRORLEVEL%% NEQ 0 ( >> "%APP_DIR%\LAUNCHER.bat"
echo     echo Starting XAMPP MySQL... >> "%APP_DIR%\LAUNCHER.bat"
echo     start "" "C:\xampp\mysql\bin\mysqld.exe" --port=3306 >> "%APP_DIR%\LAUNCHER.bat"
echo     timeout /t 3 /nobreak ^>nul >> "%APP_DIR%\LAUNCHER.bat"
echo ) else ( >> "%APP_DIR%\LAUNCHER.bat"
echo     echo MySQL already running on 3306, skipping... >> "%APP_DIR%\LAUNCHER.bat"
echo ) >> "%APP_DIR%\LAUNCHER.bat"
echo. >> "%APP_DIR%\LAUNCHER.bat"
echo :: ── START BACKEND ────────────────────────────────── >> "%APP_DIR%\LAUNCHER.bat"
echo start /min cmd /k "cd backend ^&^& node server.js" >> "%APP_DIR%\LAUNCHER.bat"
echo timeout /t 5 /nobreak ^>nul >> "%APP_DIR%\LAUNCHER.bat"
echo. >> "%APP_DIR%\LAUNCHER.bat"
echo :: ── START POS APP ────────────────────────────────── >> "%APP_DIR%\LAUNCHER.bat"
echo start "" "elara_pos.exe" >> "%APP_DIR%\LAUNCHER.bat"